### ISSUE TITLE
Only shows loading message

### ISSUE THREAD

**Issue by ricardobarantini** [ArturMroz/switcher#1]
I took this screenshot after a few minutes.

![screenshot from 2018-08-25 19-09-04](https://user-images.githubusercontent.com/1111361/44623000-81bedf80-a89a-11e8-8b47-1cb1a1128669.png)

I'm using on **Elementary OS 0.4**.

**Comment by khanfx** [comment]
Me too, w following error at the console:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ulauncher/api/client/Client.py", line 52, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python2.7/site-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/khanfx/.cache/ulauncher_cache/extensions/com.github.arturmroz.switcher/main.py", line 37, in on_event
    for window in get_active_windows():
  File "/home/khanfx/.cache/ulauncher_cache/extensions/com.github.arturmroz.switcher/main.py", line 108, in get_active_windows
    window.workspace_id = window.get_workspace().get_number() + 1
AttributeError: 'NoneType' object has no attribute 'get_number'
com.github.brpaz.ulauncher-chrome-tabs | 2018-09-01 15:19:09,528 | ERROR | __main__: on_ws_error() | Websocket connection error: [Errno 111] Connection refused
```

This is the same regardless of whether Workspace Indicator is on or off.

I'll take a look myself later and may have a pull request...

@ricardobarantini do you have the same error at the console?

Manjaro Linux here.

**Comment by ArturMroz** [comment]
Thanks for reporting. I'm able to reproduce the error, will work on it soon.

**Comment by endorama** [comment]
Hi everybody, I stumbled upon this issue and submitted a patch in PR #2
